// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpLCP488K8-KlAEsSBfp4xZ_pQHXG5Wng',
    appId: '1:636331441337:web:44a192e2f92cdbd7176f68',
    messagingSenderId: '636331441337',
    projectId: 'ad35c-619d6',
    authDomain: 'ad35c-619d6.firebaseapp.com',
    storageBucket: 'ad35c-619d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJY39bb3PgPv6zR0VpLcptNAriH908YZU',
    appId: '1:636331441337:android:d59802bdad991da1176f68',
    messagingSenderId: '636331441337',
    projectId: 'ad35c-619d6',
    storageBucket: 'ad35c-619d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqIsw4uGKcvfmADaI697i_CRl5bjkqKGM',
    appId: '1:636331441337:ios:c0e3743d62c4b4d2176f68',
    messagingSenderId: '636331441337',
    projectId: 'ad35c-619d6',
    storageBucket: 'ad35c-619d6.appspot.com',
    iosBundleId: 'utfpr.ad35c.vwallet.ad35c',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqIsw4uGKcvfmADaI697i_CRl5bjkqKGM',
    appId: '1:636331441337:ios:be2fc6ff408d86bc176f68',
    messagingSenderId: '636331441337',
    projectId: 'ad35c-619d6',
    storageBucket: 'ad35c-619d6.appspot.com',
    iosBundleId: 'utfpr.ad35c.vwallet.ad35c.RunnerTests',
  );
}
